M48
; DRILL file {KiCad 7.99.0-999-ge1db4e0694} date 2023 December 05, Tuesday 13:45:31
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-12-05T13:45:31-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.99.0-999-ge1db4e0694
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X2.2441Y-3.8189
X2.2441Y-7.5984
X19.4094Y-6.378
T0
M30
